#!/usr/bin/env python2
#encoding=UTF-8

# (C) 2014 Reid Kleiner <reid.a.kleiner@gmail.com> 
# and kevinisageek <kevinisageek.org>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
from subprocess import call
from clint.textui.colored import ColoredString
from configobj import ConfigObj
from urlparse import urlparse

if len(sys.argv)<2: sys.exit("Usage:\n donu <URL or file>")

confpath = os.getenv("HOME") + "/.donu.conf"
config = ConfigObj(confpath)
page = 0
browsers = []
indicators = []
DEBUG = config['donu']['DEBUG']
COLOR = config['donu']['COLOR']

parsed_url = urlparse(sys.argv[1])

protocol = parsed_url.scheme
if protocol == "": protocol = "file"
netloc = parsed_url.netloc

extension = parsed_url.path[parsed_url.path.rfind('.')+1:]
if extension == parsed_url.path: extension = ""

try:
    ### SCHEME ###
    defined_protocols = []
    for scheme in config: defined_protocols += [scheme]
    if DEBUG: print("Defined schemes: "+str(defined_protocols))
    while len(config[protocol])==0:
        protocol = defined_protocols[1+defined_protocols.index(protocol)]
    for program in config[protocol]:
        if str(config[protocol][program])[0] != "{":
            browsers += [str(config[protocol][program])]
            indicators += ["RESET"]
    ### LOCATION ###
    netloc = "loc:"+netloc
    defined_locations = []
    for loc in config[protocol]:
        if loc.find("loc:")==0:
            defined_locations += [loc]
    if DEBUG: print("Defined locations: "+str(defined_locations))
    if netloc in defined_locations:
        while len(config[protocol][netloc])==0:
            netloc = defined_locations[1+defined_locations.index(netloc)]
    try:
        for netloc_prog in config[protocol][netloc]:
            browsers += [str(config[protocol][netloc][netloc_prog])]
            indicators += ["RED"]
    except:
        if DEBUG: print("No subsection found for " + netloc)
    ### EXTENSION ###
    extension = "type:"+extension
    defined_types = []
    for filetype in config[protocol]:
        if filetype.find("type:")==0:
            defined_types += [filetype]
    if DEBUG: print("Defined filetypes: "+str(defined_types))
    if extension in defined_types:
        while len(config[protocol][extension])==0:
            extension = defined_types[1+defined_types.index(extension)]
    try:
        for type_prog in config[protocol][extension]:
            browsers += [str(config[protocol][extension][type_prog])]
            indicators += ["GREEN"]
    except:
        if DEBUG: print("No subsection found for type " + extension)
except KeyError:
    sys.exit("Key Error when reading " + protocol + " from " + confpath)
except:
    sys.exit("Error reading " + protocol + " from " + confpath)

def drawscreen():
    print("Giving this:\n")
    print(sys.argv[1]+"\n")
    print("To:\n")
    for i in range(0,len(browsers)):
        entry = ''
        entry += str(browsers[i])
        if i==0:
            entry += " (Default)"
        if COLOR: print(str(i+1)+ColoredString(indicators[i],"> ")+ entry)
        else: print(str(i+1)+"> "+ entry)
    #if (len(browsers)>10):
    #    print("p or n for more options")
    print("Or q to cancel")

def pass_uri(selection=1):
    call((browsers[int(selection)-1] + " " + sys.argv[1]).split())
    print("\n")
    sys.exit()

while True:
    if len(browsers) == 1:
        pass_uri()
        break
    drawscreen()

    theinput = raw_input('? ').lower()

    if theinput == '':
        theinput = '1'
    if theinput == 'e':
        print("Editing NYI")
        continue
    if theinput == 'c':
        print("Configuration NYI")
        continue
    if theinput == 'q':
        sys.exit()
    #if theinput == 'n' and len(browsers) > page * 10:
    #    page += 1
    #    continue
    #if theinput == 'p' and page > 0:
    #    page -= 1
    #    continue
    if theinput == 'r':
        sys.argv[1]+= "/.compact"
        continue

    try:
        pass_uri(theinput)
        break
    except (IndexError, ValueError):
        print("Invalid selection\n")
